# tiny-dfr config

# Display

# By default, the media layer will show the omarchy layer.
MediaLayerDefault = true
ShowButtonOutlines = false

# Disabled by default
EnablePixelShift = false

# Font
# NOTE: Will default to a non mono space font and breaks glyph icons if
# incorrect!
FontTemplate = "JetBrainsMono Nerd Font Mono:light"

# Brightness
AdaptiveBrightness = false
ActiveBrightness = 250

# Keyboard backlight
KeyboardBrightnessEnabled = true
KeyboardBrightnessStep = 1466

# Navigation
BackButtonShowOutlines = false
BackButtonOutlineColor = 0.3
ExpandableTimeoutSeconds = 10

# Primary layer (F1-F12)
PrimaryLayerKeys = [
  { Text = "F1",  Action = "F1"  },
  { Text = "F2",  Action = "F2"  },
  { Text = "F3",  Action = "F3"  },
  { Text = "F4",  Action = "F4"  },
  { Text = "F5",  Action = "F5"  },
  { Text = "F6",  Action = "F6"  },
  { Text = "F7",  Action = "F7"  },
  { Text = "F8",  Action = "F8"  },
  { Text = "F9",  Action = "F9"  },
  { Text = "F10", Action = "F10" },
  { Text = "F11", Action = "F11" },
  { Text = "F12", Action = "F12" },
]

# Media layer
MediaLayerKeys = [
  { Icon = "omarchy", Action = "Expand_Omarchy", ShowButtonOutlines = false, ButtonOutlinesColor = 0.0, Stretch = 1 },
  { Battery = "both", Action = "Battery", ShowButtonOutlines = true, Stretch = 1 },
  { Time = "%I:%M%P %-e/%m", Action = "Time", Stretch = 2, ShowButtonOutlines = false, ButtonOutlinesColor = [0.2,0.2,0.2] },
  { Text = "plugin-hyprland", Action = "Hyprland_Expand_ActiveWindow", ButtonTitle = "title", ShowAppIconAlongsideText = true, ShowButtonOutlines = false, ButtonOutlinesColor = [0.10196,0.10588,0.149019], Stretch = 6 },
  { Icon = "bolt", Action = "Expand_Trigger", ShowButtonOutlines = false, ButtonOutlinesColor = 0.0, Stretch = 1 },
  { Icon = "settings", Action = "Expand_Settings", ShowButtonOutlines = false, ButtonOutlinesColor = 0.0, Stretch = 1 },
]
