# tiny-dfr hyprland integration

Hyprland_Expand_ActiveWindow = [
    { Class = "code", LayerKeys = [
        { Icon = "command", Action = "F1", ShowButtonOutlines = true },
        { Text = "Format Document", Action = "KeyCombos_CTRL_SHIFT_I", ShowButtonOutlines = true },
    ] },

    { Class = "chromium", LayerKeys = [
        { Icon = "refresh", Action = "F5", ShowButtonOutlines = true },
        { Text = "History", Action = "KeyCombos_CTRL_H", ShowButtonOutlines = true },
        { Text = "Downloads", Action = "KeyCombos_CTRL_J", ShowButtonOutlines = true },
        { Text = "Print", Action = "KeyCombos_CTRL_P", ShowButtonOutlines = true },
        { Text = "Inspect", Action = "F12", ShowButtonOutlines = true },
    ] },

    { Class = "google-chrome", LayerKeys = [
        { Icon = "refresh", Action = "F5", ShowButtonOutlines = true },
        { Text = "History", Action = "KeyCombos_CTRL_H", ShowButtonOutlines = true },
        { Text = "Downloads", Action = "KeyCombos_CTRL_J", ShowButtonOutlines = true },
        { Text = "Print", Action = "KeyCombos_CTRL_P", ShowButtonOutlines = true },
        { Text = "Inspect", Action = "F12", ShowButtonOutlines = true },
    ] },

    { Class = "Firefox", LayerKeys = [
        { Icon = "refresh", Action = "F5", ShowButtonOutlines = true },
        { Text = "History", Action = "KeyCombos_CTRL_H", ShowButtonOutlines = true },
        { Text = "Downloads", Action = "KeyCombos_CTRL_J", ShowButtonOutlines = true },
        { Text = "Print", Action = "KeyCombos_CTRL_P", ShowButtonOutlines = true },
        { Text = "Inspect", Action = "F12", ShowButtonOutlines = true },
    ] },
]
